theme: jekyll-theme-hacker
title : Cameras And Drones
am_link: https://forums.alliedmods.net/showthread.php?t=299696
issues: https://github.com/Keplyx/cameras-and-drones/issues
cvars: https://github.com/Keplyx/cameras-and-drones/blob/master/cameras-and-drones.cfg
owner: https://keplyx.github.io/index.html
